root: true
extends: eslint:recommended
env:
  browser: false
  node: true
  es2021: true
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  indent: [error, 2]
  max-len: [warn]
  no-console: [warn]
  no-trailing-spaces: [error]
  quotes: [error, single, { avoidEscape: true }]
