name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    environment: CI
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node:
          - v17
          - v18
          - v19

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm clean-install

      - name: Compile CJS bundle
        run: npm run prepare

      - name: Test CJS package loading
        run: node -e "assert(typeof require('.').rdjpgcom === 'function')"

      - name: Run tests
        run: npm run coverage
